export const cardConstants = {
  LOADCARDS_STARTED: 'CARDS_RECEIVED',
  LOADCARDS_SUCCESS: 'CARDS_RECEIVED',
  LOADCARDS_FAIL: 'CARDS_RECEIVED',

  CARDS_RECEIVED: 'CARDS_RECEIVED',
  CARDS_INITIALIZED: 'CARDS_INITIALIZED'
};
