export const cardConstants = {
  LOADCARDS_STARTED: '  LOADCARDS_STARTED: ',
  LOADCARDS_SUCCESS: 'LOADCARDS_SUCCESS',
  LOADCARDS_FAIL: 'LOADCARDS_FAIL',

  CARDS_RECEIVED: 'CARDS_RECEIVED',
  CARDS_INITIALIZED: 'CARDS_INITIALIZED',

  LOADCARDDATALOADCARDDATA_ERROR: 'LOAD_CARD_DATA_ERROR'
};
