const _timeCards = [
    {
        id: '1',
        title: 'In progress',
        estimate: 12340,
        timeSpent: 0,
        status: 'inProgress',
        startedTime: 134132413241,
        completed: false,
        started: true,
    },
    {
        id: '2',
        title: 'Waiting for start',
        estimate: 12345,
        timeSpent: 0,
        status: 'waiting',
        startedTime: 0,
        completed: false,
        started: false,
    },
    {
        id: '3',
        title: 'Waiting for start',
        estimate: 12345,
        timeSpent: 0,
        status: 'waiting',
        startedTime: 0,
        completed: false,
        started: false,
    },
    {
        id: '4',
        title: 'Completed successfully',
        estimate: 65807,
        timeSpent: 65702,
        status: 'completed',
        startedTime: new Date().getTime(),
        completed: true,
        started: true,
    },
    {
        id: '5',
        title: 'Completed successfully',
        estimate: 65807,
        timeSpent: 65702,
        status: 'completed',
        startedTime: new Date().getTime(),
        completed: true,
        started: true,
    },
    {
        id: '6',
        title: 'Bad estimated',
        estimate: 1234,
        timeSpent: 6570200,
        status: 'badEstimated',
        startedTime: new Date().getTime(),
        completed: true,
        started: true,
    },
    {
        id: '7',
        title: 'Bad estimated',
        estimate: 1234,
        timeSpent: 6570200,
        status: 'badEstimated',
        startedTime: new Date().getTime(),
        completed: true,
        started: true,
    }
];

export {_timeCards}